name: Bug report
description: Report an issue with the modpack in its unmodified state. For other issues, use Discord.
labels: bug
title: "[BUG]"
body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue, [please search](https://github.com/StroepWafel/LYTE/issues) to make sure it has not already been reported (make sure to search closed issues as well!).

  - type: textarea
    attributes:
      label: Describe the bug
      description: Describe your issue.
    validations:
      required: true

  - type: input
    attributes:
      label: App version
      description: What version of LYTE are you using?
      placeholder: Find it by opening the config menu and clicking the about icon in the top right.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Browser
      description: Which OS are you using?
      options:
        - Linux
        - Windows
        - MacOS
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Confirm
      options:
        - label: This bug report is about an issue with the app itself. I have not modified the app nor added any unsupported code.
          required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Screenshots, video or any other information. Include logs if possible
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
