name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_channel:
        description: 'Type of release'
        required: true
        type: choice
        options:
        - Alpha
        - Beta
        - Dev
        - Release
      release_version:
        description: 'Version of release (e.g. 1.0.3), make sure to use semver (https://semver.org/)'
        required: true
        type: string
      release_summary:
        description: 'Quick summary of release to append to title'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Needed for changelog generation to see commit history

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r Src/requirements.txt

      - name: Run PyInstaller
        run: |
          python -m PyInstaller --clean --log-level=DEBUG main.spec

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: LYTE_Build
          path: dist/LYTE.exe

      - name: Set release flags
        id: flags
        shell: pwsh
        run: |
          $channel = "${{ github.event.inputs.release_channel }}"
          if ($channel -eq "Release") {
            "prerelease=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "draft=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } elseif ($channel -eq "Alpha" -or $channel -eq "Beta") {
            "prerelease=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "draft=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "prerelease=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "draft=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - name: Install Ruby (for changelog generator)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Generate changelog
        shell: bash
        run: |
          echo "# Summary: ${{ github.event.inputs.release_summary }}" > CHANGELOG.md
          gem install github_changelog_generator
          github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project ${{ github.event.repository.name }} \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --since-tag $(git describe --tags --abbrev=0 --tags --match "v*" || echo "") \
            --output TEMP_CHANGELOG.md
          type TEMP_CHANGELOG.md >> CHANGELOG.md

      - name: Create GitHub Release (with changelog)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}-${{ github.event.inputs.release_channel }}
          name: "[${{ github.event.inputs.release_channel }}] v${{ github.event.inputs.release_version }} - ${{ github.event.inputs.release_summary }}"
          body_path: CHANGELOG.md
          files: dist/LYTE.exe
          draft: ${{ steps.flags.outputs.draft }}
          prerelease: ${{ steps.flags.outputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
